### ISSUE TITLE
Need a data lineage demo notebook

### ISSUE THREAD

**Issue by MichaelTiemannOSC** [os-climate/data-platform-demo#43]
We need a notebook that demonstrates data how lineage is established at creation, and how lineage develops as tables and pipelines are joined.  For example, if tables A, B, and C are created from sources X, Y, and Z respectively, then what is the lineage of

```
F = select * from A join B on A.i=B.i
G = select i, sum(A.j * B.k)  fromC left join A on A.i=C.i left join B on B.i=C.i group by C.i
```

And other interesting cases?

**Comment by HeatherAck** [comment]
We should also include use cases involving temporary or transient tables that are dropped at the end of a session or by the user as well as changes in schema.

**Comment by caldeirav** [comment]
As explained in our Tech check in last week, we are not looking at building data lineage manually as this would not be reliable and scalable. At this point the plan is to deploy and validate pachyderm to provide automated data lineage for our pipelines. 

Also, our architecture guidelines requires all intermediate tables / steps in data pipelines to be captured so that we have transparency, traceability, reproducibility in pipeline execution.

**Comment by HeatherAck** [comment]
agreed that manual lineage is not scalable - i thought the goal of this task is to prove that the automated data lineage solution works properly by exercising various use cases (i.e. this was the "verification" task for os-climate/os_c_data_commons#50, which was to build out the production-grade capability for the os-c tools in flight).  sorry if i misunderstood the scope of these two issues.

**Comment by MichaelTiemannOSC** [comment]
Closing this issue because Vincent's tracker issue (https://github.com/os-climate/os_c_data_commons/issues/50) properly replaces this issue.
